version: '3.8'

services:
    nginx:
        image: nginx:latest
        container_name: nginx-server
        ports:
            - '5555:443'
        volumes:
            - ./dist:/usr/share/nginx/html:ro
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
            - ./certs:/etc/nginx/certs
        environment:
            - TZ=Europe/Warsaw
        entrypoint: /bin/bash -c "if [ ! -f /etc/nginx/certs/self-signed.key ]; then openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/nginx/certs/self-signed.key -out /etc/nginx/certs/self-signed.crt -subj '/CN=localhost'; fi && nginx -g 'daemon off;'"

volumes:
    certs:
